[package]
name = "bevy_flock"
version = "0.1.0"
authors = ["Trevor Sargent <trevor.a.sargent@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4" # make sure this is the latest version